import { Inter } from "next/font/google";
import "./globals.css";
import SocketConnect from "@/components/socket.io/socketConnect";
import { Body } from "@/components/body";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <SocketConnect />
      <html lang="en">
        <body suppressHydrationWarning={true} className={inter.className}>
          <Body>
            {children}
          </Body>
        </body>
      </html>
    </>
  );
}
