name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull ronakkaria01/next-file-sharing-cicd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f next-file-sharing-cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name next-file-sharing-cicd-pipeline-container ronakkaria01/next-file-sharing-cicd