name: CI Pipeline

on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create .env File
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "NEXT_PUBLIC_PORT=${{ secrets.NEXT_PUBLIC_PORT }}" >> .env
    - name: Login Dockerhub
      env:
            DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
            DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
    - name: List Files
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ronakkaria01/next-file-sharing-cicd
    - name: Push to Dockerhub
      run: docker push ronakkaria01/next-file-sharing-cicd:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Pull Docker image
      run: sudo docker pull ronakkaria01/next-file-sharing-cicd:latest
    - name: Delete Old docker container
      run: sudo docker rm -f next-file-sharing-cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name next-file-sharing-cicd-pipeline-container ronakkaria01/next-file-sharing-cicd