name: CI/CD Pipeline

on:
    push:
        branches: [ "main" ]

    workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create .env File
      run: |
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "NEXT_PUBLIC_PORT=${{ secrets.NEXT_PUBLIC_PORT }}" >> .env
        echo "NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}" >> .env
        echo "NEXT_PUBLIC_DOCKER_IP=${{ secrets.NEXT_PUBLIC_DOCKER_IP }}" >> .env
    - name: List Files
      run: ls -la
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ronakkaria01/next-file-sharing-cicd
    - name: Check docker compose
      run: sudo docker ps

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Delete Old docker container
      run: sudo docker rm -f next-file-sharing-cicd-pipeline-container || true
    - name: Prune Docker
      run: sudo docker system prune
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name next-file-sharing-cicd-pipeline-container ronakkaria01/next-file-sharing-cicd